version: '2'

services:
  minio:
    image: minio/minio:latest 
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - "${ARCHIVE_FOLDER}:/data"
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=passpass

  telescreen:
    image: panfio/telescreen:latest
    environment:
      - MINIO_URL=http://minio:9000
      - KAFKA_BOOTSTRAPADDRESS=kafka:9094
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8990
      - ZUUL_ROUTES_ADMIN=http://admin:8990
      - ZUUL_ROUTES_DATA=http://data:8111
      - ZUUL_ROUTES_HANDLER=http://handler:8222
    ports:
      - 8888:8080
    links:
      - minio
      - kafka
      - admin
      - data
      - handler
  
  data:
    image: panfio/telescreen:data-latest
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - KAFKA_BOOTSTRAPADDRESS=kafka:9094
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8990
    links:
      - kafka
      - admin
  
  handler:
    image: panfio/telescreen:handler-latest
    environment:
      - KAFKA_BOOTSTRAPADDRESS=kafka:9094
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8990
      - SERVER_ZONEOFFSET=3
    links:
      - kafka
      - admin

  admin:
    image: panfio/telescreen:admin-latest
    environment:
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:8990
    ports:
      - 8999:8990

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # volumes: 
    #   - "${ARCHIVE_FOLDER}/mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passpass

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "wellbeing:1:1,video:1:1,music:1:1,timelog:1:1,mifit:1:1,message:1:1,call:1:1,media:1:1,autotimer:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1   # dev

      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENERS: INSIDE://localhost:9092,OUTSIDE://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

###
### DEV utils
###

  # sonar:
  #   image: sonarqube:7.9.1-community
  #   ports:
  #     - 9001:9000
  #     - 9092:9092

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: passpass
  