version: '2'

services:
  minio:
    image: minio/minio:latest 
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - "${ARCHIVE_FOLDER}:/data"
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=passpass

  telescreen:
    image: panfio/telescreen:latest
    environment:
      - MINIO_URL=http://minio:9000
      # - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin:9090
    ports:
      - 8888:8080
    links:
      - minio
      # - admin

  # admin:
  #   image: panfio/admin:latest
  #   ports:
  #     - 9999:9090
  