---
apiVersion: apps/v1beta1
kind: Deployment 
metadata: 
  name: "{{ .Chart.Name }}-handler"  
spec: 
  strategy:
    type: RollingUpdate 
  replicas: 1 
  template: 
    metadata:
      labels:
        service: "{{ .Chart.Name }}-handler"  
    spec:  
      imagePullSecrets:  
      - name: regsecret 
      containers:  
      - name: "{{ .Chart.Name }}-handler"  
        image: panfio/telescreen:handler-latest
        ports:
        - containerPort: 8222 
          protocol: TCP 
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8222 
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8222
        #   initialDelaySeconds: 10
        # resources:  
        #   requests:   
        #     memory: {{ .Values.reqmem }} 
        #     cpu: {{ .Values.reqcpu }} 
        #   limits: 
        #     memory: {{ .Values.limmem }}
        #     cpu: {{ .Values.limcpu }} 
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "{{ .Values.javaToolOptions }}"
          - name: MINIO_URL
            value: http://minio:9000
          - name: SPRING_DATA_MONGODB_HOST
            value: mongodb
          - name: KAFKA_BOOTSTRAPADDRESS
            value: kafka:9092
          - name: SERVER_ZONEOFFSET
            value: "{{ .Values.zoneOffset }}"
          - name: SPRING_BOOT_ADMIN_CLIENT_URL
            value: http://admin:8990

---  
apiVersion: v1  
kind: Service  
metadata:  
  name: "handler"  
spec:  
  type: ClusterIP  
  selector:
    service: "{{ .Chart.Name }}-handler" 
  ports:  
  - name: http 
    port: 8222 
    targetPort: 8222
    protocol: TCP 