spring.application.name: "telescreen"

server:
  port: 8080

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    admin:
      url: http://localhost:8990
    data:
      url: http://localhost:8111
    handler:
      url: http://localhost:8222


##### MAIN PROPS #####
spring.security:
  user:
    name: "user"
    password: "passpass"

spring.boot:
  admin:
    client:
      url: http://localhost:8990
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      instance.metadata.user.name: ${spring.security.user.name}
      instance.metadata.user.password: ${spring.security.user.password}

kafka:
  bootstrapAddress: localhost:9092

management:
  endpoints.web.exposure.include: health, status, env, metrics, trace, jolokia, info, configprops
  endpoint.health.show-details: always
