server:
  port: 8080
  #url: "http://localhost:8080"

minio:
  url: "http://localhost:9000"
  access-key: "user"
  secret-key: "passpass"
  bucket: "app"

spring:
  application.name: "Telescreen"
  #boot.admin.client.url: "http://localhost:9090"
  security:
    user:
      name: "user"
      password: "passpass"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "user"
    password: "passpass"
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#management:
#  security.enabled: false
#  endpoints.web.exposure.include: *
#  endpoint.health.show-details: always
