server:
  port: 8080
  #url: "http://localhost:8080"

minio:
  url: "http://localhost:9000"
  access-key: "user"
  secret-key: "passpass"
  bucket: "app"

spring:
  application.name: "Telescreen"
  #boot.admin.client.url: "http://localhost:9090"
  security:
    user:
      name: "user"
      password: "passpass"
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: user
      password: passpass
      database: telescreen

#management:
#  security.enabled: false
#  endpoints.web.exposure.include: *
#  endpoint.health.show-details: always
