spring.application.name: "handler"

server:
  port: 8222

minio:
  url: "http://localhost:9000"
  access-key: "user"
  secret-key: "passpass"
  bucket: "app"

##### MAIN PROPS #####
spring.security:
  user:
    name: "user"
    password: "passpass"

spring.boot:
  admin:
    client:
      url: http://localhost:8990
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      instance.metadata.user.name: ${spring.security.user.name}
      instance.metadata.user.password: ${spring.security.user.password}

kafka:
  bootstrapAddress: localhost:9092

management:
  security.enabled: false
  endpoints.web.exposure.include: health, status, env, metrics, trace, jolokia, info, configprops
  endpoint.health.show-details: always
##### MAIN PROPS #####