name: docker-publish

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push
      run: |
        ./scripts/build.sh
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker push panfio/telescreen:latest
        docker push panfio/telescreen:handler-latest
        docker push panfio/telescreen:data-latest
        docker push panfio/telescreen:admin-latest
