name: tests-and-checkstyle

on:
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        cd telescreen
        ./mvnw -B compile test
    - name: Checkstyle
      run: |
        cd telescreen
        ./mvnw -B checkstyle:check
